version: "2"

services:
  wordpress_dev:
    image: "jamesc/wordpressdev-php7.4:latest"
    container_name: "wordpressdev-php7.4-webdev"
    ports:
      - "8100:80"
    environment:
      VIRTUAL_HOST: "wordpress.dev"
      WORDPRESS_SITE_TITLE: "wordpressdev"
      WORDPRESS_SITE_URL: "http://wordpress.dev"
      WORDPRESS_DB_HOST: "wordpressdev-php7.4-mysqldev"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: "wordpress"
    depends_on:
      - "mysql_wordpressdev"
    networks:
      - "front"
      - "back"
    volumes:
      - "./wordpressdev:/var/www/html/"

  mysql_wordpressdev:
    image: "mysql:5.7"
    container_name: "wordpressdev-php7.4-mysqldev"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3310:3306"
    networks:
      - "back"

networks:
  front: {}
  back: {}