version: "2"

services:
  wordpress_dev:
    image: "jamesc/wordpressdev-php7.2:latest"
    container_name: "wordpressdev-php7.2-webdev"
    ports:
      - "8100:80"
    environment:
      VIRTUAL_HOST: "wordpress.dev"
      WORDPRESS_SITE_TITLE: "wordpressdev"
      WORDPRESS_SITE_URL: "http://wordpress.dev"
      WORDPRESS_DB_HOST: "wordpressdev-php7.2-mysqldev"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: "wordpress"
    depends_on:
      - "mysql_wordpressdev"
    networks:
      - "front"
      - "back"
    volumes:
      - "./wp:/var/www/html/"

  mysql_wordpressdev:
    image: "mysql:5.7"
    container_name: "wordpressdev-php7.2-mysqldev"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3310:3306"
    networks:
      - "back"

#  personally I prefer to use Heidi SQL but you could add a phpmyadmin container
  # phpmyadmin_wordpressdev:
  #   image: "phpmyadmin/phpmyadmin"
  #   container_name: "wordpressdev-php7.2-phpmyadmindev"
  #   links:
  #     - "mysql_wordpressdev"
  #   environment:
  #     MYSQL_USER: "root"
  #     MYSQL_PASSWORD: ""
  #     MYSQL_ROOT_PASSWORD: ""
  #   restart: "always"
  #   ports:
  #     - "8101:80"
  #   networks:
  #     - "back"

networks:
  front: {}
  back: {}